# Generated by Django 4.1.4 on 2023-11-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_post_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='product_type',
            field=models.CharField(choices=[('top_sellers', 'Top Sellers'), ('new_releases', 'New Releases'), ('old_releases', 'Old Releases'), ('top', 'Top'), ('Event', 'Event'), ('gadget', 'Gadget')], max_length=20),
        ),
    ]
