# Generated by Django 4.1.4 on 2023-11-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_post_aboutgame_post_developer_post_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='youtubeurl',
            field=models.TextField(default=''),
        ),
    ]
