# Generated by Django 4.1.4 on 2023-12-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_showcaseimages_post_showcaseimage1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('giftcardimage', models.ImageField(default='/logo.png', null=True, upload_to='files/')),
                ('region', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('giftcard_type', models.CharField(choices=[('top_sellers', 'Top Sellers'), ('new_releases', 'New Releases'), ('old_releases', 'Old Releases'), ('top', 'Top'), ('Event', 'Event'), ('gadget', 'Gadget'), ('giftcards', 'giftcards')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='product_type',
            field=models.CharField(choices=[('top_sellers', 'Top Sellers'), ('new_releases', 'New Releases'), ('old_releases', 'Old Releases'), ('top', 'Top'), ('Event', 'Event'), ('gadget', 'Gadget'), ('giftcards', 'giftcards')], max_length=20),
        ),
    ]
