# Generated by Django 4.1.4 on 2023-12-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_giftcard_alter_post_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='giftcard_type',
            field=models.CharField(choices=[('PSN', 'psn'), ('stream', 'stream'), ('xbox live', 'xbox live'), ('nintendo', 'nintendo'), ('ea app', 'ea app'), ('microsoft', 'microsoft'), ('riot', 'giftcards'), ('blizzard', 'blizzard'), ('levelup', 'levelup')], max_length=20),
        ),
    ]
